name: Auto Publish
on:
  release:
    types: [ created ]
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: central
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Set version
        run: |
          VERSION=${{ github.event.release.tag_name }}
          ./gradlew -Pversion=$VERSION
      - name: Publish package
        run: ./gradlew publish --no-daemon --stacktrace --info --warning-mode=all
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_KEY: ${{ secrets.GPG_KEY }}