name: Auto Publish
on:
  release:
    types: [ created ]
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: central
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Publish package
        run: ./gradlew -Pversion=${{ github.event.release.tag_name }} publishToCentralPortal --no-daemon --stacktrace --info --warning-mode=all
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSPHRASE }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_KEY }}